name: Telegram Forwarder

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: [ push , pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Send Telegram Message
      uses: ./
      with:
        token: ${{ secrets.token }}
        message: ${{ secrets.message }}
        recipient: ${{ secrets.recipient }}
